USE master;
GO

--DROP AND RECREATE THE 'DATAWAREHOUSE' DATABASE
IF EXISTS(SELECT 1 FROM sys.databases where name = 'DataWareHouse')
BEGIN 
	ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE DATAWAREHOUSE
END;
GO

CREATE DATABASE DATAWAREHOUSE

USE DATAWAREHOUSE

CREATE SCHEMA BRONZE
CREATE SCHEMA SILVER
GO
CREATE SCHEMA GOLD
GO
